<div class="error-code">
    <h1>503</h1>
</div>

<div class="error-message">
    <h2><?php $this->translate($this->message) ?></h2>
</div>

<?php if (isset($this->display_exceptions) && $this->display_exceptions): ?>
<div class="error-exceptions">
    <?php if(isset($this->exception) && $this->exception instanceof Exception): ?>
    <h3><?php echo $this->translate('Additional information') ?>:</h3>
    <h4><?php echo get_class($this->exception); ?></h4>
    <dl>
        <dt><?php echo $this->translate('File') ?>:</dt>
        <dd>
            <pre class="prettyprint linenums"><?php echo $this->exception->getFile() ?>:<?php echo $this->exception->getLine() ?></pre>
        </dd>
        <dt><?php echo $this->translate('Message') ?>:</dt>
        <dd>
            <pre class="prettyprint linenums"><?php echo $this->exception->getMessage() ?></pre>
        </dd>
        <dt><?php echo $this->translate('Stack trace') ?>:</dt>
        <dd>
            <pre class="prettyprint linenums"><?php echo $this->exception->getTraceAsString() ?></pre>
        </dd>
    </dl>
    <?php
        $e = $this->exception->getPrevious();
        if ($e) :
    ?>
    <hr/>
    <h3><?php echo $this->translate('Previous exceptions') ?>:</h3>
    <ul class="unstyled">
        <?php while($e) : ?>
        <li>
            <h4><?php echo get_class($e); ?></h4>
            <dl>
                <dt><?php echo $this->translate('File') ?>:</dt>
                <dd>
                    <pre class="prettyprint linenums"><?php echo $e->getFile() ?>:<?php echo $e->getLine() ?></pre>
                </dd>
                <dt><?php echo $this->translate('Message') ?>:</dt>
                <dd>
                    <pre class="prettyprint linenums"><?php echo $e->getMessage() ?></pre>
                </dd>
                <dt><?php echo $this->translate('Stack trace') ?>:</dt>
                <dd>
                    <pre class="prettyprint linenums"><?php echo $e->getTraceAsString() ?></pre>
                </dd>
            </dl>
        </li>
        <?php
            $e = $e->getPrevious();
            endwhile;
        ?>
    </ul>
    <?php endif; ?>

    <?php else: ?>

    <h4><?php echo $this->translate('No Exception available') ?></h4>

    <?php endif ?>

</div>
<?php endif ?>
